version: '3.8'  

services:
  central-server:
    build: ./central_server
    ports:
      - "5000:5000"
    networks:  
      - fl-network

  client1:
    build: ./client
    networks:
      - fl-network
    depends_on:
      - central-server

  client2:
    build: ./client
    networks:
      - fl-network
    depends_on:
      - central-server

networks:
  fl-network:
    driver: bridge